version: "3"
services:

  ############# Notes: backend store for edX Student Notes
  notes:
    image: $(OPENEDX_DOCKER_NAMESPACE:-regis)/$(OPENEDX_DOCKER_IMAGE_PREFIX:-'')openedx-notes:$(OPENEDX_DOCKER_TAG:-hawthorn)
    build:
      context: ./notes
    networks:
      default:
        aliases:
          - notes.openedx
    volumes:
      - ./config/notes:/openedx/config
      - ./data/notes:/openedx/data
    restart: unless-stopped
    depends_on:
      - mysql
