version: "3"
services:

  ############# Xqueue: external grading of Open edX problems
  xqueue:
    image: $(OPENEDX_DOCKER_NAMESPACE:-regis)/$(OPENEDX_DOCKER_IMAGE_PREFIX:-'')openedx-xqueue:$(OPENEDX_DOCKER_TAG:-hawthorn)
    build:
      context: ./xqueue
    volumes:
      - ./config/xqueue:/openedx/config
      - ./data/xqueue:/openedx/data
    restart: unless-stopped
    depends_on:
      - mysql

  xqueue_consumer:
    image: $(OPENEDX_DOCKER_NAMESPACE:-regis)/$(OPENEDX_DOCKER_IMAGE_PREFIX:-'')openedx-xqueue:$(OPENEDX_DOCKER_TAG:-hawthorn)
    build:
      context: ./xqueue
    volumes:
      - ./config/xqueue:/openedx/config
      - ./data/xqueue:/openedx/data
    restart: unless-stopped
    # Run 12 workers per queue
    command: ./manage.py run_consumer 12
    depends_on:
      - mysql
