version: "3"
services:

  android:
    image: $(OPENEDX_DOCKER_NAMESPACE:-regis)/$(OPENEDX_DOCKER_IMAGE_PREFIX:-'')openedx-android:$(OPENEDX_DOCKER_TAG:-hawthorn)
    build:
      context: ./android
    volumes:
      - ./config/android/:/openedx/config/
      - ./data/android/:/openedx/data
